/* BBS presentation: engine-derived dimensions, semantic forms and schedule markup. */
window.SiteQuant.bbsView = (() => {
  const { escape: html, icon } = window.SiteQuant.ui;
  const model = window.SiteQuant.bbsModel;
  const format = (value, digits = 3) => Number(value).toLocaleString('en-IN', { minimumFractionDigits: digits, maximumFractionDigits: digits });
  const badge = (text, modifier = '') => `<span class="bbs-badge ${modifier ? `bbs-badge--${modifier}` : ''}">${text}</span>`;

  function diagram(code, dimensions = null, compact = false) {
    let geometry = {
      A: { path: 'M35 62H225', dimensions: [['L', 130, 101]], guides: 'M35 76v25M225 76v25M35 94h190M31 98l8-8M221 98l8-8' },
      B: { path: 'M45 25V76H220', dimensions: [['A', 134, 109], ['B', 22, 52]], guides: 'M45 88v20M220 88v20M45 100h175M41 104l8-8M216 104l8-8M32 25H14M32 76H14M21 25v51' },
      C: { path: 'M45 25V76H215V25', dimensions: [['A', 130, 108], ['B', 20, 52], ['C', 239, 52]], guides: 'M45 87v19M215 87v19M45 99h170M41 103l8-8M211 103l8-8M32 25H15M32 76H15M22 25v51M227 25h17M227 76h17M237 25v51' },
      D: { path: 'M20 80H80L130 37H215V80', dimensions: [['A', 50, 106], ['B', 64, 57], ['C', 105, 17], ['D', 172, 17], ['E', 244, 61]], guides: 'M20 91v15M80 91v15M20 99h60M80 28V8M130 28V8M215 28V8M80 23h135M72 37H60M72 80H60M67 37v43M225 37h16M225 80h16M235 37v43' },
    }[code];
    if (!geometry) {
      const planned = { E:'M45 28H215V92H45Z', F:'M55 28H205V92H55Z', G:'M130 24a42 42 0 1 0 0.1 0', H:'M45 28V92H215V55', J:'M38 76H190Q220 76 220 45', K:'M45 28H215V92H45Z', P:'M68 30q62 20 0 40t0 40', Q:'M50 30V92H210V30', R:'M55 90V35H105V90M155 90V35H205V90', S:'M35 88H85L130 38H225', T:'M35 62H225' }[code] || 'M35 62H225';
      geometry = { path: planned, dimensions: [], guides: '' };
    }
    const name = model.shapeOptions.find(shape => shape.code === code)?.name;
    return `<svg class="bbs-diagram ${compact ? 'bbs-diagram--compact' : ''}" viewBox="0 0 260 120" role="img" aria-label="${html(name)} bar, schematic not to scale"><path class="bbs-diagram-guides" d="${geometry.guides}"/><path class="bbs-diagram-bar" d="${geometry.path}"/>${geometry.dimensions.map(([label, x, y]) => `<text x="${x}" y="${y}" text-anchor="middle">${label}</text>`).join('')}</svg>${dimensions && !compact ? `<dl class="bbs-dimension-readout">${Object.entries(dimensions).map(([label, value]) => `<div><dt>${html(label)}</dt><dd>${format(value, 1)} <span>mm</span></dd></div>`).join('')}</dl>` : ''}`;
  }

  function field(input, key, label, unit = '', { text = false, min = '0', step = 'any', hint = '' } = {}) {
    return `<div class="bbs-field"><label for="bbs-${key}">${label}${unit ? `<span>${unit}</span>` : ''}</label><div class="bbs-input-wrap"><input class="bbs-input" id="bbs-${key}" name="${key}" data-bbs-field="${key}" type="${text ? 'text' : 'number'}" ${text ? `maxlength="${key === 'description' ? 240 : 80}"` : `min="${min}" step="${step}" inputmode="decimal"`} value="${html(input[key])}" required aria-describedby="bbs-${key}-error${hint ? ` bbs-${key}-hint` : ''}" ${text ? 'autocomplete="off"' : ''}>${unit ? `<span aria-hidden="true">${unit}</span>` : ''}</div>${hint ? `<small id="bbs-${key}-hint" class="bbs-field-hint">${hint}</small>` : ''}<p class="bbs-field-error" id="bbs-${key}-error"></p></div>`;
  }

  function select(input, key, label, options) {
    return `<div class="bbs-field"><label for="bbs-${key}">${label}</label><select class="bbs-input" id="bbs-${key}" name="${key}" data-bbs-field="${key}" aria-describedby="bbs-${key}-error">${options.map(option => `<option ${input[key] === option ? 'selected' : ''}>${html(option)}</option>`).join('')}</select><p class="bbs-field-error" id="bbs-${key}-error"></p></div>`;
  }

  function parameters(input) {
    if (input.shape === 'B') return `<div class="bbs-fields bbs-fields--three">${field(input, 'ret', 'Return length', 'mm', { min: '0.1' })}</div><p class="bbs-field-hint">Engine A comes from the clear bar-axis length; B uses the return length.</p>`;
    if (input.shape === 'D') return `<div class="bbs-fields bbs-fields--three">${field(input, 'rise', 'Crank rise', 'mm', { min: '0.1' })}${field(input, 'run', 'Crank run', 'mm', { min: '0.1' })}${field(input, 'tail', 'Tail', 'mm', { min: '0.1' })}</div><p class="bbs-field-hint">A: clear bar-axis length · B: rise · C: run · D: clear distribution width · E: tail. The framework adds these five terms; it does not calculate an inclined segment length. This is not a fabrication detail.</p>`;
    if (['E','F'].includes(input.shape)) return `<div class="bbs-fields bbs-fields--three">${field(input, 'stirrupWidth', 'Width — centreline', 'mm', { min: '0.1' })}${field(input, 'stirrupDepth', 'Depth — centreline', 'mm', { min: '0.1' })}${field(input, 'hookAngle', 'Hook angle — reference', '°', { min: '0' })}${field(input, 'hookExtension', 'Hook extension 1 — specified', 'mm', { min: '0' })}${field(input, 'hookExtension2', 'Hook extension 2 — specified', 'mm', { min: '0' })}</div><p class="bbs-field-hint">The engine uses the stated centreline dimensions plus specified extensions. Hook angle is recorded for review; no bend allowance is inferred.</p>`;
    if (input.shape === 'G') return `<div class="bbs-fields bbs-fields--three">${field(input, 'ringDiameter', 'Diameter — centreline', 'mm', { min: '0.1' })}${field(input, 'ringCount', 'Rings per member', 'nos', { min: '1', step: '1' })}${field(input, 'hookExtension', 'Closure extension 1 — specified', 'mm', { min: '0' })}${field(input, 'hookExtension2', 'Closure extension 2 — specified', 'mm', { min: '0' })}</div><p class="bbs-field-hint">The engine uses π × the stated centreline diameter plus specified closure extensions. No bend allowance is inferred.</p>`;
    return `<p class="bbs-field-hint">${input.shape === 'C' ? 'A, B and C are derived by the engine from member geometry and clear cover.' : 'L is derived by the engine from the bar-axis length and clear cover.'} No additional shape inputs required.</p>`;
  }

  function shapeLibrary() {
    const item = shape => `<button type="button" class="bbs-library-item" data-bbs-shape="${shape.code}" data-bbs-library-item="${html(`${shape.name} ${shape.category} ${shape.applicableMembers.join(' ')}`).toLowerCase()}" aria-pressed="false"><span class="bbs-library-diagram">${diagram(shape.code, null, true)}</span><span><b>${shape.code} · ${html(shape.name)}</b><small>${html(shape.applicableMembers.join(' · '))}</small><em>${shape.calculation === 'engine' ? 'Engine available' : 'Calculation engine planned'}</em></span><i>${html(shape.plan)}</i></button>`;
    return `<section class="bbs-shape-library" aria-labelledby="bbs-shape-library-title"><div class="bbs-library-heading"><div><p class="sq-eyebrow">SHAPE LIBRARY</p><h2 id="bbs-shape-library-title">Select a reinforcement shape</h2></div><label class="bbs-library-search">${icon('search')}<span class="sq-sr-only">Search shape library</span><input id="bbs-shape-search" type="search" placeholder="Search shape or member"></label></div><p class="bbs-library-note">Library geometry and engineering calculations are intentionally separate. Planned shapes cannot generate a schedule result.</p>${['COMMON','BENDS','STIRRUPS & LINKS','SPECIAL'].map(category => `<section class="bbs-library-group"><h3>${category}</h3><div>${model.shapeOptions.filter(shape => shape.category === category).map(item).join('')}</div></section>`).join('')}<section class="bbs-library-group bbs-library-group--premium"><h3>PREMIUM · ROADMAP</h3><p>Professional: links, ties, rings, hooks, hairpins, chairs and advanced templates. Team / Contractor: cutting lists, wastage, revisions, approvals, locked schedules and collaboration. Backend-dependent workflows are planned.</p></section></section>`;
  }

  function form(input) {
    return `<form class="bbs-editor sq-surface" id="bbs-editor" novalidate>
      <div class="bbs-editor-heading"><span class="sq-eyebrow">CALCULATION INPUTS</span><span id="bbs-editor-mode">New calculation</span></div>
      <fieldset class="bbs-fieldset"><legend><span>01</span> Member</legend><div class="bbs-fields">${select(input, 'memberType', 'Member type', model.members)}${select(input, 'family', 'Reinforcement family', model.families)}${field(input, 'mark', 'Bar mark', '', { text: true })}<div class="bbs-field-wide">${field(input, 'description', 'Description', '', { text: true })}</div>${select(input, 'material', 'Steel grade', model.grades)}${select(input, 'revision', 'Revision', ['Draft','Revision 1','Revision 2'])}</div></fieldset><fieldset class="bbs-fieldset"><legend><span>02</span> Review workflow</legend><div class="bbs-fields">${select(input, 'reviewStatus', 'Review status', ['Draft','Calculated','Review Required','Reviewed','Approved'])}${field(input, 'reviewedBy', 'Reviewed by', '', { text: true })}${field(input, 'reviewDate', 'Review date', '', { text: true })}<div class="bbs-field-wide">${field(input, 'reviewNote', 'Review note', '', { text: true })}</div></div><p class="bbs-field-hint">Approved is workflow state only, not code compliance or construction certification.</p></fieldset>
      <fieldset class="bbs-fieldset"><legend><span>02</span> Geometry</legend><div class="bbs-fields bbs-fields--three">${field(input, 'length', 'Length', 'm', { min: '0.001' })}${field(input, 'breadth', 'Breadth', 'm', { min: '0.001' })}${field(input, 'depth', 'Depth', 'm', { min: '0.001' })}</div><div class="bbs-fields">${field(input, 'cover', 'Clear cover', 'mm')}${field(input, 'quantity', 'Identical members', 'nos', { min: '1', step: '1' })}</div></fieldset>
      <fieldset class="bbs-fieldset"><legend><span>03</span> Reinforcement</legend><div class="bbs-fields bbs-fields--three">${field(input, 'dia', 'Bar diameter', 'mm', { min: '0.1' })}${field(input, 'spacing', 'Spacing', 'mm c/c', { min: '0.1' })}${select(input, 'direction', 'Direction', model.directions)}</div><p class="bbs-field-hint" id="bbs-direction-hint"></p></fieldset>
      <fieldset class="bbs-fieldset bbs-fieldset--last"><legend><span>04</span> Selected shape</legend><div class="bbs-shapes" role="group" aria-label="Implemented bar shapes">${model.shapeOptions.filter(shape => shape.calculation === 'engine').map(shape => `<button type="button" class="bbs-shape" data-bbs-shape="${shape.code}" aria-pressed="${input.shape === shape.code}" aria-label="${shape.code} — ${html(shape.name)}"><span class="bbs-shape-code">${shape.code}</span>${diagram(shape.code, null, true)}<strong>${html(shape.name)}</strong></button>`).join('')}</div><div id="bbs-shape-parameters">${parameters(input)}</div></fieldset>
      <div class="bbs-editor-actions"><span id="bbs-form-feedback" role="status" aria-live="polite">Changes update the calculation, not scheduled rows.</span><button class="sq-button sq-button--primary" type="submit" id="bbs-add-item">${icon('plus')} Add BBS item</button></div>
    </form>${shapeLibrary()}`;
  }

  function result(assessment, input, traceOpen = true) {
    const r = assessment.result;
    if (!r) return `<div class="bbs-result-heading"><span class="sq-eyebrow">CALCULATION VERIFICATION</span>${badge(assessment.planned ? 'ENGINE PLANNED' : 'INPUT REQUIRED', 'error')}</div><h2 id="bbs-result-title" tabindex="-1">${assessment.planned ? 'Calculation engine planned' : 'Calculation paused'}</h2><p class="bbs-result-empty">${assessment.errors.calculation || 'Correct the marked fields to calculate. No previous result will be exported while inputs are invalid.'}</p><div class="bbs-result-review">${icon('review')} Engineering review required</div>`;
    const o = r.output;
    const metrics = [['Bars / member', o.barsPerMember, 'bars', 'barsPerMember'], ['Total bars', o.totalBars, 'bars', 'totalBars'], ['Cutting length', format(o.cuttingLengthM), 'm', 'cuttingLengthM'], ['Unit weight', format(o.unitWeightKgPerM), 'kg/m', 'unitWeightKgPerM'], ['Total length', format(o.totalLengthM), 'm', 'totalLengthM'], ['Total weight', format(o.totalWeightKg, 2), 'kg', 'totalWeightKg'], ['Total tonnes', format(o.totalWeightTonnes), 't', 'totalWeightTonnes']];
    return `<div class="bbs-result-heading"><span class="sq-eyebrow">CALCULATION VERIFICATION</span>${badge('CALCULATED', 'calculated')}</div><h2 id="bbs-result-title" tabindex="-1">${html(input.mark)} <span>· ${html(input.memberType)}</span></h2><div class="bbs-drawing">${diagram(input.shape, r.input.dimensionsMm)}<p>Schematic only · not to scale</p></div><dl class="bbs-result-metrics">${metrics.map(([label, value, unit, key]) => `<div${key === 'totalWeightKg' ? ' class="bbs-result-weight"' : ''}><dt>${label}</dt><dd><strong data-bbs-output="${key}">${value}</strong><span>${unit}</span></dd></div>`).join('')}</dl><div class="bbs-result-review">${icon('review')} REVIEW REQUIRED</div><details class="bbs-trace" ${traceOpen ? 'open' : ''}><summary>Calculation trace</summary><ol>${r.trace.map(line => `<li>${html(line)}</li>`).join('')}</ol></details><dl class="bbs-engine-metadata"><div><dt>Formula version</dt><dd>${html(r.engineVersion)}</dd></div><div><dt>Bending / fixing</dt><dd>${html(r.standards.bendingFixing)}</dd></div><div><dt>Concrete reference</dt><dd>${html(r.standards.concreteReference)}</dd></div></dl><p class="bbs-standard-status">${html(r.standards.status)}</p><div class="bbs-export-readiness">${icon('check')}<span>READY FOR EXPORT<small>CSV data only. Not approved for construction issue.</small></span></div>`;
  }

  function scheduleRows(rows, selected, editingId) {
    return rows.map(row => {
      const r = model.calculate(row.input).result;
      if (!r) return '';
      const i = row.input, o = r.output;
      return `<tr class="bbs-row${selected.has(row.id) ? ' bbs-row--selected' : ''}${editingId === row.id ? ' bbs-row--editing' : ''}" data-bbs-row="${html(row.id)}"><td><input type="checkbox" data-bbs-select="${html(row.id)}" aria-label="Select ${html(i.mark)}" ${selected.has(row.id) ? 'checked' : ''}></td><th scope="row"><button class="bbs-mark-link" data-bbs-edit="${html(row.id)}">${html(i.mark)}</button><small>${row.kind === 'sample' ? 'Sample data' : 'Browser-local draft'}</small></th><td>${html(i.memberType)}</td><td>${html(i.family || 'Bottom main')}</td><td class="bbs-description-cell">${html(i.description)}<small>${html(i.material)} · ${html(i.direction)}</small></td><td><span class="bbs-table-shape">${diagram(i.shape, null, true)}<span>${i.shape}</span></span></td><td class="bbs-number">${html(i.dia)}<small>mm</small></td><td class="bbs-number">${html(i.spacing)}<small>mm c/c</small></td><td class="bbs-number">${o.totalBars}</td><td class="bbs-number">${format(o.cuttingLengthM)}<small>m</small></td><td class="bbs-number">${format(o.totalLengthM)}<small>m</small></td><td class="bbs-number">${format(o.totalWeightKg, 2)}<small>kg</small></td><td>${badge(i.reviewStatus || 'Needs Review', 'review')}<small>${html(i.revision || 'Draft')}</small></td></tr>`;
    }).join('') || '<tr><td colspan="12" class="bbs-schedule-empty">No items in this view. Clear filters or add a valid BBS item.</td></tr>';
  }

  function schedule() {
    return `<section class="bbs-schedule sq-surface" aria-labelledby="bbs-schedule-title"><div class="bbs-schedule-heading"><div><p class="sq-eyebrow">PROJECT REGISTER</p><h2 id="bbs-schedule-title">BBS schedule <span class="sq-count" id="bbs-row-count"></span></h2><p>Calculated records. Every item still requires engineering review.</p></div><button class="sq-button sq-button--secondary" data-bbs-action="export-schedule" id="bbs-export-schedule">${icon('exports')} Export view</button></div><div class="bbs-schedule-toolbar"><label class="bbs-search">${icon('search')}<span class="sq-sr-only">Search BBS schedule</span><input type="search" id="bbs-search" placeholder="Search mark, family, member…"></label><label class="bbs-filter">Source<select id="bbs-filter"><option value="all">All items</option><option value="local">Browser-local drafts</option><option value="sample">Sample data</option></select></label><label class="bbs-filter">Group<select id="bbs-group"><option value="none">No grouping</option><option value="member">Member</option><option value="dia">Diameter</option><option value="shape">Shape</option></select></label><label class="bbs-filter">Sort<select id="bbs-sort"><option value="mark-asc">Mark A–Z</option><option value="mark-desc">Mark Z–A</option><option value="weight-desc">Weight: high to low</option><option value="weight-asc">Weight: low to high</option><option value="saved-desc">Recently saved</option></select></label></div><div id="bbs-summaries" class="bbs-summaries"></div><div class="bbs-selection-bar"><span id="bbs-selection-label" aria-live="polite">No items selected</span><div><button class="bbs-text-action" data-bbs-action="duplicate" id="bbs-duplicate" disabled>Duplicate selected</button><button class="bbs-text-action bbs-text-action--delete" data-bbs-action="delete" id="bbs-delete" disabled>Delete selected</button><button class="bbs-text-action" data-bbs-action="new">${icon('plus')} New item</button></div></div><div class="bbs-table-scroll" role="region" aria-label="BBS schedule table, scroll horizontally for more columns" tabindex="0"><table class="bbs-table"><thead><tr><th scope="col"><input type="checkbox" id="bbs-select-all" aria-label="Select all visible BBS items"></th><th scope="col">Mark</th><th scope="col">Member</th><th scope="col">Family</th><th scope="col">Description</th><th scope="col">Shape</th><th scope="col">Dia</th><th scope="col">Spacing</th><th scope="col">Qty</th><th scope="col">Cut length</th><th scope="col">Total length</th><th scope="col">Weight</th><th scope="col">Status</th></tr></thead><tbody id="bbs-schedule-body"></tbody></table></div><div class="bbs-schedule-foot"><span id="bbs-visible-count"></span><span>All quantities calculated by the versioned engine · CSV exports include formula version</span></div></section>`;
  }

  function render(projects, project, workspace) {
    return `<section class="bbs-workspace" aria-labelledby="bbs-title"><div class="bbs-context"><label>Project<select id="bbs-project">${projects.map(p => `<option value="${html(p.id)}" ${p.id === project.id ? 'selected' : ''}>${html(p.name)}</option>`).join('')}</select></label><span class="bbs-context-separator" aria-hidden="true">/</span><div><span>Structure / block</span><strong>${html(project.block || 'Unassigned block')}</strong></div><span class="bbs-context-origin">${project.local ? 'Browser-local project' : 'Sample project context'}</span></div><div class="bbs-page-heading"><div><p class="sq-eyebrow">ENGINEERING WORKSPACE</p><h1 id="bbs-title">Bar bending schedule</h1><p>Build the bar. Verify the calculation. Assemble the schedule.</p></div><div class="bbs-top-actions"><button class="sq-button sq-button--secondary" data-bbs-action="save">Save draft</button><button class="sq-button sq-button--primary" id="bbs-export-current" data-bbs-action="export-current">${icon('exports')} Export CSV</button></div></div><div class="bbs-state-bar"><div id="bbs-calculation-state" aria-live="polite"></div><span id="bbs-save-status">Browser-local workspace · no cloud sync</span></div><p class="bbs-storage-notice" id="bbs-storage-notice" role="status" hidden></p><div class="bbs-mobile-summary" id="bbs-mobile-summary"></div><div class="bbs-engineering-layout">${form(workspace.draft)}<aside class="bbs-result sq-surface" id="bbs-result" aria-label="Live engineering result"></aside></div>${schedule()}<p class="bbs-issue-disclaimer">${icon('review')} Prototype calculation framework. Engineering review required before construction issue.</p><span class="sq-sr-only" id="bbs-live-status" role="status" aria-live="polite"></span><dialog class="sq-dialog" id="bbs-delete-dialog" aria-labelledby="bbs-delete-title"><h2 id="bbs-delete-title">Delete selected schedule items?</h2><p id="bbs-delete-description"></p><p>This removes the selected rows from this browser-local schedule. No cloud data is affected.</p><div class="sq-dialog-actions"><button class="sq-button sq-button--secondary" data-bbs-action="cancel-delete">Cancel</button><button class="sq-button sq-button--primary" data-bbs-action="confirm-delete">Delete items</button></div></dialog><dialog class="sq-dialog" id="bbs-replace-dialog" aria-labelledby="bbs-replace-title"><h2 id="bbs-replace-title">Replace the current editor?</h2><p>Your unscheduled inputs will be replaced. Add or update a schedule item first if you want to keep them in the schedule.</p><div class="sq-dialog-actions"><button class="sq-button sq-button--secondary" data-bbs-action="cancel-replace">Keep editing</button><button class="sq-button sq-button--primary" data-bbs-action="confirm-replace">Replace inputs</button></div></dialog></section>`;
  }
  return { render, result, parameters, scheduleRows, format, badge };
})();
