/* Versioned calculation engine. UI catalog and rendering must not contain engineering maths. */
const ENGINE_VERSION='bbs-v0.5-u-shape-clarity';
const REVIEW_STATUS='framework — engineering review required';
const meta={bendingFixing:'IS 2502:1963 (reference basis)',concreteReference:'IS 456:2000 + amendments',status:REVIEW_STATUS};
const SHAPES={
 STRAIGHT:{code:'A',name:'Straight',dimensions:['L'],build:({L})=>L,trace:({L})=>[`L = ${L} mm (clear bar-axis length)`]},
 L_BAR:{code:'B',name:'L bar',dimensions:['A','B'],build:({A,B})=>A+B,trace:({A,B})=>[`A = ${A} mm (clear bar-axis length)`,`B = ${B} mm (specified return)`,`Cut length = A + B`]},
 U_BAR:{code:'C',name:'U bar / inverted U',dimensions:['A','B','C'],build:({A,B,C})=>A+B+C,trace:({A,B,C})=>[`Base = ${A} mm (specified clear bar-axis length)`,`Leg 1 = ${B} mm (specified)`,`Leg 2 = ${C} mm (specified)`,`Cut length = Base + Leg 1 + Leg 2`]},
 CRANKED:{code:'D',name:'Cranked / bent-up',dimensions:['A','B','C','D','E'],build:({A,B,C,D,E})=>A+B+C+D+E,trace:({A,B,C,D,E})=>[`A = ${A} mm (clear length)`,`B = ${B} mm (specified rise)`,`C = ${C} mm (specified run)`,`D = ${D} mm (clear breadth)`,`E = ${E} mm (specified tail)`,`Cut length = A + B + C + D + E (framework additive dimensions)`]},
 RECTANGULAR_STIRRUP:{code:'E',name:'Rectangular stirrup / link',dimensions:['W','D','H1','H2','BA'],build:({W,D,H1,H2,BA})=>2*W+2*D+BA+H1+H2,trace:linkTrace},
 COLUMN_TIE:{code:'F',name:'Closed column link',dimensions:['W','D','H1','H2','BA'],build:({W,D,H1,H2,BA})=>2*W+2*D+BA+H1+H2,trace:linkTrace},
 CIRCULAR_RING:{code:'G',name:'Circular ring',dimensions:['D','H1','H2'],build:({D,H1,H2})=>Math.PI*D+H1+H2,trace:({D,H1,H2})=>[`D = ${D} mm (centreline diameter)`,`Circumference = π × D = ${round(Math.PI*D,1)} mm`,`Hook/closure extensions = ${H1} + ${H2} mm (specified)`,`Cut length = πD + H1 + H2`]}
};
function positive(v,l){const n=Number(v);if(!Number.isFinite(n)||n<0)throw Error(`${l} must be non-negative.`);return n}
function nonzero(v,l){const n=positive(v,l);if(n<=0)throw Error(`${l} must be greater than zero.`);return n}
function integer(v,l,min=1){const n=Number(v);if(!Number.isSafeInteger(n)||n<min)throw Error(`${l} must be a whole number of at least ${min}.`);return n}
function round(v,d=3){const p=10**d;return Math.round(v*p)/p}
function unitWeightKgPerM(d){return d*d/162}
function numberOfBars(clear,spacing){if(spacing<=0)throw Error('Spacing must be greater than zero.');return clear<=0?1:Math.floor(clear/spacing)+1}
function hooks(i){const h=i.hooks||{};return {H1:positive(h.hookExtensionMm??0,'Hook extension 1'),H2:positive(h.hookExtension2Mm??h.hookExtensionMm??0,'Hook extension 2')}}
function linkTrace({W,D,H1,H2,BA}){return [`Straight portions = 2 × ${W} + 2 × ${D} = ${round(2*W+2*D,1)} mm (converted centreline dimensions)`,`Bend contribution / allowance = ${BA} mm (explicitly specified; none inferred)`,`Hook extensions = ${H1} + ${H2} = ${round(H1+H2,1)} mm`,`Cut length = straight portions + bend contribution + hook extensions = ${round(2*W+2*D+BA+H1+H2,1)} mm`]}
function linkDetailing(i,d){const h=i.hooks||{},mode=String(i.linkDetailingMode||'DRAWING_SPECIFIED'),allowed=['GENERAL_IS2502_REFERENCE','SEISMIC_IS13920_2016','DRAWING_SPECIFIED','CUSTOM'];if(!allowed.includes(mode))throw Error('Choose a supported link detailing basis.');const hookCount=integer(h.hookCount??2,'Hook count',1),bendCount=integer(h.bendCount??4,'Bend count',0),angle=nonzero(h.hookAngleDeg??135,'Hook angle'),bendAllowance=positive(h.bendAllowanceMm??0,'Bend contribution / allowance');let H1,H2,rule,reference;if(mode==='SEISMIC_IS13920_2016'){if(angle!==135)throw Error('IS 13920:2016 seismic link detailing requires a 135° hook.');H1=H2=Math.max(6*d,65);rule='max(6d, 65 mm)';reference='IS 13920:2016 seismic link detailing';}else if(mode==='GENERAL_IS2502_REFERENCE'){const min=8*d;H1=Math.max(positive(h.hookExtensionMm??min,'Hook extension 1'),min);H2=Math.max(positive(h.hookExtension2Mm??h.hookExtensionMm??min,'Hook extension 2'),min);rule='minimum straight portion beyond end curve: 8d';reference='IS 2502:1963 clause 3.8 reference';}else{H1=nonzero(h.hookExtensionMm,'Hook extension 1');H2=nonzero(h.hookExtension2Mm??h.hookExtensionMm,'Hook extension 2');rule=mode==='DRAWING_SPECIFIED'?'drawing-specified extension':'custom explicit extension';reference=mode==='DRAWING_SPECIFIED'?'Project drawing / engineer specification':'Custom project instruction';}if(hookCount!==2)throw Error('This closed-link model currently requires exactly two hook extensions.');return{mode,hookCount,bendCount,angle,H1,H2,bendAllowance,rule,reference};}
function centrelineDimension(value,basis,dia,label){const raw=nonzero(value,label);if(basis==='INNER')return raw+dia;if(basis==='OUTER'){const converted=raw-dia;if(converted<=0)throw Error(`${label} must exceed bar diameter when using outer dimensions.`);return converted;}return raw;}
function dimensions(i,c){const L=nonzero(i.lengthMm,'Member length'),B=nonzero(i.breadthMm,'Member breadth'),D=nonzero(i.depthMm,'Member depth'),dia=nonzero(i.diaMm,'Bar diameter'),h=i.hooks||{};switch(i.shape){
 case'STRAIGHT':return{L:Math.max(0,L-2*c)};
 case'L_BAR':return{A:Math.max(0,L-2*c),B:nonzero(h.returnLengthMm??Math.max(dia*12,300),'Return length')};
 case'U_BAR':{const base=nonzero(h.uBaseLengthMm??Math.max(0,L-2*c),'U bar base length'),leg1=nonzero(h.uLeg1Mm??Math.max(0,D-2*c),'U bar leg 1'),leg2=nonzero(h.uLeg2Mm??Math.max(0,D-2*c),'U bar leg 2');return{A:base,B:leg1,C:leg2};}
 case'CRANKED':return{A:Math.max(0,L-2*c),B:nonzero(h.crankRiseMm??Math.max(dia*10,150),'Crank rise'),C:nonzero(h.crankRunMm??Math.max(dia*10,150),'Crank run'),D:Math.max(0,B-2*c),E:nonzero(h.tailMm??Math.max(dia*10,150),'Tail length')};
 case'RECTANGULAR_STIRRUP':case'COLUMN_TIE':{if(c*2>=B||c*2>=D)throw Error('Cover must leave a positive member dimension.');const basis=String(i.dimensionBasis||'CENTRELINE'),allowed=['CENTRELINE','INNER','OUTER','DRAWING_SPECIFIED'];if(!allowed.includes(basis))throw Error('Choose a supported dimension basis.');const W=centrelineDimension(i.stirrupWidthMm??B-2*c,basis,dia,'Stirrup width'),H=centrelineDimension(i.stirrupDepthMm??D-2*c,basis,dia,'Stirrup depth'),detail=linkDetailing(i,dia);return{W,D:H,H1:detail.H1,H2:detail.H2,BA:detail.bendAllowance,detail,basis}}
 case'CIRCULAR_RING':{const ring=nonzero(i.ringDiameterMm??B-2*c,'Ring centreline diameter');if(c*2>=B)throw Error('Cover must leave a positive ring centreline diameter.');return{D:ring,...hooks(i)}}
 default:throw Error(`Unsupported shape: ${i.shape}`)}}
function calculateBbs(i){const c=positive(i.coverMm??0,'Clear cover'),d=nonzero(i.diaMm,'Bar diameter'),s=nonzero(i.spacingMm,'Spacing'),q=integer(i.memberQuantity??1,'Number of identical members'),shape=SHAPES[i.shape];if(!shape)throw Error(`Unsupported shape: ${i.shape}`);const L=nonzero(i.lengthMm,'Member length'),B=nonzero(i.breadthMm,'Member breadth'),D=nonzero(i.depthMm,'Member depth'),dist=nonzero(i.distributionDimensionMm??B,'Distribution dimension'),clear=Math.max(0,dist-2*c),bars=i.barCountPerMember===undefined?numberOfBars(clear,s):integer(i.barCountPerMember,'Bars per member'),dims=dimensions(i,c),cut=shape.build(dims),uw=unitWeightKgPerM(d),totalBars=bars*q,totalLength=(cut/1000)*totalBars,totalWeight=totalLength*uw,link=dims.detail,{detail,basis,...dimensionValues}=dims;return{engineVersion:ENGINE_VERSION,standards:meta,assumptions:['All dimensions follow the labels supplied with the calculation input.','U-bar base and leg lengths are explicit dimensions; they are not inferred from unrelated member axes when supplied.','For links, bend contribution is an explicit input; bend radii, bend allowances, anchorage and code-specific detailing are not inferred.','Engineering review required before construction issue.'],input:{memberType:i.memberType,mark:i.mark,description:i.description,material:i.material,lengthMm:L,breadthMm:B,depthMm:D,coverMm:c,diaMm:d,spacingMm:s,memberQuantity:q,shape:shape.code,shapeName:shape.name,dimensionsMm:dimensionValues,linkDetailing:link&&{dimensionBasis:basis,hookAngleDeg:link.angle,hookExtensionRule:link.rule,hookExtensionMm:link.H1,hookExtension2Mm:link.H2,hookCount:link.hookCount,bendCount:link.bendCount,bendAllowanceMm:link.bendAllowance,detailingBasis:link.reference}},output:{barsPerMember:bars,totalBars,cuttingLengthMm:round(cut,1),cuttingLengthM:round(cut/1000,3),unitWeightKgPerM:round(uw,3),totalLengthM:round(totalLength,3),totalWeightKg:round(totalWeight,2),totalWeightTonnes:round(totalWeight/1000,3)},trace:[`Clear distribution = ${round(clear,1)} mm`,`Bars / member = ${i.barCountPerMember===undefined?`floor(${round(clear,1)} / ${s}) + 1 = ${bars}`:`specified ${bars}`}`,...(link?[`Detailing basis = ${link.reference}`,`Dimension basis = ${basis}`,`Hook angle = ${link.angle}°`,`Extension rule = ${link.rule}`,`Hook extension = ${link.rule==='max(6d, 65 mm)'?`max(6 × ${d}, 65) = ${link.H1}`:link.H1} mm`,`Hook count = ${link.hookCount}; bend count = ${link.bendCount}`]:[]),...shape.trace(dims),`Unit weight = ${d}² / 162 = ${round(uw,3)} kg/m`,`Total bars = ${bars} × ${q} = ${totalBars}`,`Total length = ${totalBars} × ${round(cut,1)} / 1000 = ${round(totalLength,3)} m`,`Total weight = ${round(totalLength,3)} × ${round(uw,3)} = ${round(totalWeight,2)} kg`]}}
if(typeof module!=='undefined')module.exports={calculateBbs,SHAPES,ENGINE_VERSION,unitWeightKgPerM};
