/* Versioned calculation engine. UI catalog and rendering must not contain engineering maths. */
const ENGINE_VERSION='bbs-v0.3-framework';
const REVIEW_STATUS='framework — engineering review required';
const meta={bendingFixing:'IS 2502:1963',concreteReference:'IS 456:2000 + amendments',status:REVIEW_STATUS};
const SHAPES={
 STRAIGHT:{code:'A',name:'Straight',dimensions:['L'],build:({L})=>L,trace:({L})=>[`L = ${L} mm (clear bar-axis length)`]},
 L_BAR:{code:'B',name:'L bar',dimensions:['A','B'],build:({A,B})=>A+B,trace:({A,B})=>[`A = ${A} mm (clear bar-axis length)`,`B = ${B} mm (specified return)`,`Cut length = A + B`]},
 U_BAR:{code:'C',name:'U bar / inverted U',dimensions:['A','B','C'],build:({A,B,C})=>A+B+C,trace:({A,B,C})=>[`A = ${A} mm (clear length)`,`B = ${B} mm (clear depth)`,`C = ${C} mm (clear breadth)`,`Cut length = A + B + C`]},
 CRANKED:{code:'D',name:'Cranked / bent-up',dimensions:['A','B','C','D','E'],build:({A,B,C,D,E})=>A+B+C+D+E,trace:({A,B,C,D,E})=>[`A = ${A} mm (clear length)`,`B = ${B} mm (specified rise)`,`C = ${C} mm (specified run)`,`D = ${D} mm (clear breadth)`,`E = ${E} mm (specified tail)`,`Cut length = A + B + C + D + E (framework additive dimensions)`]},
 RECTANGULAR_STIRRUP:{code:'E',name:'Rectangular stirrup',dimensions:['W','D','H1','H2'],build:({W,D,H1,H2})=>2*W+2*D+H1+H2,trace:({W,D,H1,H2})=>[`W = ${W} mm (centreline width)`,`D = ${D} mm (centreline depth)`,`Hook extensions = ${H1} + ${H2} mm (specified)`,`Cut length = 2W + 2D + H1 + H2`]},
 COLUMN_TIE:{code:'F',name:'Closed column tie',dimensions:['W','D','H1','H2'],build:({W,D,H1,H2})=>2*W+2*D+H1+H2,trace:({W,D,H1,H2})=>[`W = ${W} mm (centreline width)`,`D = ${D} mm (centreline depth)`,`Hook extensions = ${H1} + ${H2} mm (specified)`,`Cut length = 2W + 2D + H1 + H2`]},
 CIRCULAR_RING:{code:'G',name:'Circular ring',dimensions:['D','H1','H2'],build:({D,H1,H2})=>Math.PI*D+H1+H2,trace:({D,H1,H2})=>[`D = ${D} mm (centreline diameter)`,`Circumference = π × D = ${round(Math.PI*D,1)} mm`,`Hook/closure extensions = ${H1} + ${H2} mm (specified)`,`Cut length = πD + H1 + H2`]}
};
function positive(v,l){const n=Number(v);if(!Number.isFinite(n)||n<0)throw Error(`${l} must be non-negative.`);return n}
function nonzero(v,l){const n=positive(v,l);if(n<=0)throw Error(`${l} must be greater than zero.`);return n}
function integer(v,l,min=1){const n=Number(v);if(!Number.isSafeInteger(n)||n<min)throw Error(`${l} must be a whole number of at least ${min}.`);return n}
function round(v,d=3){const p=10**d;return Math.round(v*p)/p}
function unitWeightKgPerM(d){return d*d/162}
function numberOfBars(clear,spacing){if(spacing<=0)throw Error('Spacing must be greater than zero.');return clear<=0?1:Math.floor(clear/spacing)+1}
function hooks(i){const h=i.hooks||{};return {H1:positive(h.hookExtensionMm??0,'Hook extension 1'),H2:positive(h.hookExtension2Mm??h.hookExtensionMm??0,'Hook extension 2')}}
function dimensions(i,c){const L=nonzero(i.lengthMm,'Member length'),B=nonzero(i.breadthMm,'Member breadth'),D=nonzero(i.depthMm,'Member depth'),dia=nonzero(i.diaMm,'Bar diameter'),h=i.hooks||{};switch(i.shape){
 case'STRAIGHT':return{L:Math.max(0,L-2*c)};
 case'L_BAR':return{A:Math.max(0,L-2*c),B:nonzero(h.returnLengthMm??Math.max(dia*12,300),'Return length')};
 case'U_BAR':return{A:Math.max(0,L-2*c),B:Math.max(0,D-2*c),C:Math.max(0,B-2*c)};
 case'CRANKED':return{A:Math.max(0,L-2*c),B:nonzero(h.crankRiseMm??Math.max(dia*10,150),'Crank rise'),C:nonzero(h.crankRunMm??Math.max(dia*10,150),'Crank run'),D:Math.max(0,B-2*c),E:nonzero(h.tailMm??Math.max(dia*10,150),'Tail length')};
 case'RECTANGULAR_STIRRUP':case'COLUMN_TIE':{const W=nonzero(i.stirrupWidthMm??B-2*c,'Stirrup centreline width'),H=nonzero(i.stirrupDepthMm??D-2*c,'Stirrup centreline depth');if(c*2>=B||c*2>=D)throw Error('Cover must leave a positive stirrup centreline dimension.');return{W,D:H,...hooks(i)}}
 case'CIRCULAR_RING':{const ring=nonzero(i.ringDiameterMm??B-2*c,'Ring centreline diameter');if(c*2>=B)throw Error('Cover must leave a positive ring centreline diameter.');return{D:ring,...hooks(i)}}
 default:throw Error(`Unsupported shape: ${i.shape}`)}}
function calculateBbs(i){const c=positive(i.coverMm??0,'Clear cover'),d=nonzero(i.diaMm,'Bar diameter'),s=nonzero(i.spacingMm,'Spacing'),q=integer(i.memberQuantity??1,'Number of identical members'),shape=SHAPES[i.shape];if(!shape)throw Error(`Unsupported shape: ${i.shape}`);const L=nonzero(i.lengthMm,'Member length'),B=nonzero(i.breadthMm,'Member breadth'),D=nonzero(i.depthMm,'Member depth'),dist=nonzero(i.distributionDimensionMm??B,'Distribution dimension'),clear=Math.max(0,dist-2*c),bars=i.barCountPerMember===undefined?numberOfBars(clear,s):integer(i.barCountPerMember,'Bars per member'),dims=dimensions(i,c),cut=shape.build(dims),uw=unitWeightKgPerM(d),totalBars=bars*q,totalLength=(cut/1000)*totalBars,totalWeight=totalLength*uw;return{engineVersion:ENGINE_VERSION,standards:meta,assumptions:['All dimensions follow the labels supplied with the calculation input.','Bend allowances, bend radii, anchorage and code-specific detailing are not inferred.','Engineering review required before construction issue.'],input:{memberType:i.memberType,mark:i.mark,description:i.description,material:i.material,lengthMm:L,breadthMm:B,depthMm:D,coverMm:c,diaMm:d,spacingMm:s,memberQuantity:q,shape:shape.code,shapeName:shape.name,dimensionsMm:dims},output:{barsPerMember:bars,totalBars,cuttingLengthMm:round(cut,1),cuttingLengthM:round(cut/1000,3),unitWeightKgPerM:round(uw,3),totalLengthM:round(totalLength,3),totalWeightKg:round(totalWeight,2),totalWeightTonnes:round(totalWeight/1000,3)},trace:[`Clear distribution = ${round(clear,1)} mm`,`Bars / member = ${i.barCountPerMember===undefined?`floor(${round(clear,1)} / ${s}) + 1 = ${bars}`:`specified ${bars}`}`,...shape.trace(dims),`Unit weight = ${d}² / 162 = ${round(uw,3)} kg/m`,`Total bars = ${bars} × ${q} = ${totalBars}`,`Total length = ${totalBars} × ${round(cut,1)} / 1000 = ${round(totalLength,3)} m`,`Total weight = ${round(totalLength,3)} × ${round(uw,3)} = ${round(totalWeight,2)} kg`]}}
if(typeof module!=='undefined')module.exports={calculateBbs,SHAPES,ENGINE_VERSION,unitWeightKgPerM};
