const assert=require('node:assert/strict');const{calculateBbs,unitWeightKgPerM}=require('./bbs-engine');
const r=calculateBbs({memberType:'Beam',mark:'B12-01',description:'Bottom main',material:'Fe 500D',lengthMm:4200,breadthMm:300,depthMm:450,coverMm:25,diaMm:16,spacingMm:150,memberQuantity:1,distributionDimensionMm:300,shape:'STRAIGHT'});assert.equal(r.output.barsPerMember,2);assert.equal(r.output.totalBars,2);assert.equal(r.output.cuttingLengthMm,4150);assert.equal(r.output.unitWeightKgPerM,Number((16*16/162).toFixed(3)));
const l=calculateBbs({memberType:'Slab',mark:'S04-11',description:'Distribution',material:'Fe 500D',lengthMm:4000,breadthMm:3000,depthMm:150,coverMm:20,diaMm:10,spacingMm:200,memberQuantity:2,distributionDimensionMm:3000,shape:'L_BAR',hooks:{returnLengthMm:300}});assert.equal(l.output.barsPerMember,15);assert.equal(l.output.totalBars,30);assert.equal(l.output.cuttingLengthMm,4260);assert.equal(unitWeightKgPerM(12),144/162);
const base={memberType:'Beam',mark:'X',description:'test',material:'Fe 500D',lengthMm:4000,breadthMm:300,depthMm:500,coverMm:25,diaMm:10,spacingMm:150,memberQuantity:2,distributionDimensionMm:300};
const stirrup=calculateBbs({...base,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'SEISMIC_IS13920_2016',dimensionBasis:'CENTRELINE',hooks:{hookAngleDeg:135}});assert.equal(stirrup.input.shape,'E');assert.equal(stirrup.output.cuttingLengthMm,1400);assert.equal(stirrup.output.totalBars,4);assert.equal(stirrup.output.totalLengthM,5.6);assert.equal(stirrup.output.totalWeightKg,3.46);assert.equal(stirrup.input.linkDetailing.hookExtensionMm,100);assert.equal(stirrup.input.linkDetailing.totalBendDeductionMm,120);assert.ok(stirrup.trace.some(x=>x.includes('Centreline perimeter')));
const tie=calculateBbs({...base,shape:'COLUMN_TIE',stirrupWidthMm:250,stirrupDepthMm:450,linkDetailingMode:'SEISMIC_IS13920_2016',dimensionBasis:'CENTRELINE',hooks:{hookAngleDeg:135}});assert.equal(tie.input.shape,'F');assert.equal(tie.output.cuttingLengthMm,1480);assert.equal(tie.input.linkDetailing.hookExtensionMm,100);
for(const [dia,extension,cut] of [[8,75,1384],[10,100,1400],[12,120,1416],[16,160,1448]]){const seismic=calculateBbs({...base,diaMm:dia,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'SEISMIC_IS13920_2016',dimensionBasis:'CENTRELINE',hooks:{hookAngleDeg:135}});assert.equal(seismic.input.linkDetailing.hookExtensionMm,extension);assert.equal(seismic.input.linkDetailing.hookExtension2Mm,extension);assert.equal(seismic.output.cuttingLengthMm,cut);}
const drawing=calculateBbs({...base,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'DRAWING_SPECIFIED',dimensionBasis:'INNER',hooks:{hookAngleDeg:135,hookExtensionMm:90,hookExtension2Mm:100}});assert.equal(drawing.input.dimensionsMm.W,250);assert.equal(drawing.input.dimensionsMm.D,450);assert.equal(drawing.output.cuttingLengthMm,1470);
const custom=calculateBbs({...base,shape:'COLUMN_TIE',stirrupWidthMm:260,stirrupDepthMm:460,linkDetailingMode:'CUSTOM',dimensionBasis:'OUTER',hooks:{hookAngleDeg:135,hookExtensionMm:95,hookExtension2Mm:105}});assert.equal(custom.input.dimensionsMm.W,250);assert.equal(custom.input.dimensionsMm.D,450);assert.equal(custom.output.cuttingLengthMm,1480);
const ninety=calculateBbs({...base,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'DRAWING_SPECIFIED',dimensionBasis:'CENTRELINE',hooks:{hookAngleDeg:90,hookExtensionMm:80,hookExtension2Mm:80}});assert.equal(ninety.output.cuttingLengthMm,1340);assert.equal(ninety.input.linkDetailing.hookBendDeductionMm,20);
const u=calculateBbs({...base,memberType:'Footing',shape:'U_BAR',hooks:{uBaseLengthMm:2300,uLeg1Mm:500,uLeg2Mm:500}});assert.equal(u.output.cuttingLengthMm,3300);assert.equal(u.input.dimensionsMm.A,2300);assert.equal(u.input.dimensionsMm.B,500);assert.equal(u.input.dimensionsMm.C,500);
const inverted=calculateBbs({...base,memberType:'Footing',shape:'U_BAR',hooks:{uBaseLengthMm:1800,uLeg1Mm:600,uLeg2Mm:700}});assert.equal(inverted.output.cuttingLengthMm,3100);
assert.throws(()=>calculateBbs({...base,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'SEISMIC_IS13920_2016',hooks:{hookAngleDeg:90}}));
assert.throws(()=>calculateBbs({...base,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'DRAWING_SPECIFIED',hooks:{hookAngleDeg:135}}));
assert.throws(()=>calculateBbs({...base,diaMm:0,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'SEISMIC_IS13920_2016',hooks:{hookAngleDeg:135}}));
const ring=calculateBbs({...base,memberType:'Column',shape:'CIRCULAR_RING',ringDiameterMm:300,barCountPerMember:3,hooks:{hookExtensionMm:50,hookExtension2Mm:50}});assert.equal(ring.input.shape,'G');assert.equal(ring.output.barsPerMember,3);assert.equal(ring.output.totalBars,6);assert.equal(ring.output.cuttingLengthMm,1042.5);assert.ok(ring.trace.some(x=>x.includes('π')));
for(const input of [{shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:0,stirrupDepthMm:100},{shape:'COLUMN_TIE',stirrupWidthMm:100,stirrupDepthMm:-1},{shape:'CIRCULAR_RING',ringDiameterMm:0},{shape:'CIRCULAR_RING',ringDiameterMm:250,barCountPerMember:0},{shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:100,stirrupDepthMm:100,spacingMm:0},{shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:100,stirrupDepthMm:100,coverMm:200}])assert.throws(()=>calculateBbs({...base,...input}));
console.log('BBS engine checks passed.');
