const ENGINE_VERSION='bbs-v0.2-framework';
const SHAPES={
 STRAIGHT:{code:'A',name:'Straight',dimensions:['L'],buildLengthMm:({L})=>L,trace:({L})=>[`L = ${L} mm`]},
 L_BAR:{code:'B',name:'L bar',dimensions:['A','B'],buildLengthMm:({A,B})=>A+B,trace:({A,B})=>[`A = ${A} mm`,`B = ${B} mm`,`Cut length = A + B`]},
 U_BAR:{code:'C',name:'U bar',dimensions:['A','B','C'],buildLengthMm:({A,B,C})=>A+B+C,trace:({A,B,C})=>[`A = ${A} mm`,`B = ${B} mm`,`C = ${C} mm`,`Cut length = A + B + C`]},
 CRANKED:{code:'D',name:'Cranked',dimensions:['A','B','C','D','E'],buildLengthMm:({A,B,C,D,E})=>A+B+C+D+E,trace:({A,B,C,D,E})=>[`A = ${A} mm`,`B = ${B} mm`,`C = ${C} mm`,`D = ${D} mm`,`E = ${E} mm`,`Cut length = A + B + C + D + E`]}
};
function positive(v,l){const n=Number(v);if(!Number.isFinite(n)||n<0)throw Error(`${l} must be non-negative.`);return n}
function integer(v,l,min=1){const n=Math.floor(Number(v));if(!Number.isFinite(n)||n<min)throw Error(`${l} must be at least ${min}.`);return n}
function round(v,d=3){const p=10**d;return Math.round(v*p)/p}
function unitWeightKgPerM(d){return d*d/162}
function numberOfBars(clear,spacing){if(spacing<=0)throw Error('Spacing must be greater than zero.');return clear<=0?1:Math.floor(clear/spacing)+1}
function dimensions(i,c){const L=positive(i.lengthMm,'Member length'),B=positive(i.breadthMm,'Member breadth'),D=positive(i.depthMm,'Member depth'),dia=positive(i.diaMm,'Bar diameter'),h=i.hooks||{};switch(i.shape){case'STRAIGHT':return{L:Math.max(0,L-2*c)};case'L_BAR':return{A:Math.max(0,L-2*c),B:positive(h.returnLengthMm??Math.max(dia*12,300),'Return length')};case'U_BAR':return{A:Math.max(0,L-2*c),B:Math.max(0,D-2*c),C:Math.max(0,B-2*c)};case'CRANKED':return{A:Math.max(0,L-2*c),B:positive(h.crankRiseMm??Math.max(dia*10,150),'Crank rise'),C:positive(h.crankRunMm??Math.max(dia*10,150),'Crank run'),D:Math.max(0,B-2*c),E:positive(h.tailMm??Math.max(dia*10,150),'Tail length')};default:throw Error(`Unsupported shape: ${i.shape}`)}}
function calculateBbs(i){const c=positive(i.coverMm??0,'Clear cover'),d=positive(i.diaMm,'Bar diameter'),s=positive(i.spacingMm,'Spacing'),q=integer(i.memberQuantity??1,'Number of identical members'),dist=positive(i.distributionDimensionMm??i.breadthMm,'Distribution dimension');if(!SHAPES[i.shape])throw Error(`Unsupported shape: ${i.shape}`);const clear=Math.max(0,dist-2*c),bars=numberOfBars(clear,s),dims=dimensions(i,c),shape=SHAPES[i.shape],cut=shape.buildLengthMm(dims),uw=unitWeightKgPerM(d),totalBars=bars*q,totalLength=(cut/1000)*totalBars,totalWeight=totalLength*uw;return{engineVersion:ENGINE_VERSION,standards:{bendingFixing:'IS 2502:1963',concreteReference:'IS 456:2000 + amendments',status:'framework — engineering review required'},input:{memberType:i.memberType,mark:i.mark,description:i.description,material:i.material,lengthMm:positive(i.lengthMm,'Member length'),breadthMm:positive(i.breadthMm,'Member breadth'),depthMm:positive(i.depthMm,'Member depth'),coverMm:c,diaMm:d,spacingMm:s,memberQuantity:q,shape:shape.code,shapeName:shape.name,dimensionsMm:dims},output:{barsPerMember:bars,totalBars,cuttingLengthMm:round(cut,1),cuttingLengthM:round(cut/1000,3),unitWeightKgPerM:round(uw,3),totalLengthM:round(totalLength,3),totalWeightKg:round(totalWeight,2),totalWeightTonnes:round(totalWeight/1000,3)},trace:[`Clear distribution = ${round(clear,1)} mm`,`Bars / member = floor(${round(clear,1)} / ${s}) + 1 = ${bars}`,...shape.trace(dims),`Unit weight = ${d}² / 162 = ${round(uw,3)} kg/m`,`Total bars = ${bars} × ${q} = ${totalBars}`,`Total length = ${totalBars} × ${round(cut,1)} / 1000 = ${round(totalLength,3)} m`,`Total weight = ${round(totalLength,3)} × ${round(uw,3)} = ${round(totalWeight,2)} kg`]}}
if(typeof module!=='undefined')module.exports={calculateBbs,SHAPES,ENGINE_VERSION,unitWeightKgPerM};
