const assert=require('node:assert/strict');const{calculateBbs,unitWeightKgPerM}=require('./bbs-engine');
const r=calculateBbs({memberType:'Beam',mark:'B12-01',description:'Bottom main',material:'Fe 500D',lengthMm:4200,breadthMm:300,depthMm:450,coverMm:25,diaMm:16,spacingMm:150,memberQuantity:1,distributionDimensionMm:300,shape:'STRAIGHT'});assert.equal(r.output.barsPerMember,2);assert.equal(r.output.totalBars,2);assert.equal(r.output.cuttingLengthMm,4150);assert.equal(r.output.unitWeightKgPerM,Number((16*16/162).toFixed(3)));
const l=calculateBbs({memberType:'Slab',mark:'S04-11',description:'Distribution',material:'Fe 500D',lengthMm:4000,breadthMm:3000,depthMm:150,coverMm:20,diaMm:10,spacingMm:200,memberQuantity:2,distributionDimensionMm:3000,shape:'L_BAR',hooks:{returnLengthMm:300}});assert.equal(l.output.barsPerMember,15);assert.equal(l.output.totalBars,30);assert.equal(l.output.cuttingLengthMm,4280);assert.equal(unitWeightKgPerM(12),144/162);
const u=calculateBbs({memberType:'Footing',mark:'F1',description:'U bar',material:'Fe 500D',lengthMm:2400,breadthMm:2400,depthMm:600,coverMm:50,diaMm:12,spacingMm:200,memberQuantity:1,distributionDimensionMm:2400,shape:'U_BAR',hooks:{uBaseLengthMm:2300,uLeg1Mm:500,uLeg2Mm:500}});assert.equal(u.output.cuttingLengthMm,3300);assert.equal(u.input.shape,'C');assert.equal(u.input.shapeName,'U bar / inverted U');
const stirrupBase={memberType:'Beam',mark:'X',description:'test',material:'Fe 500D',lengthMm:4000,breadthMm:300,depthMm:500,coverMm:25,diaMm:10,spacingMm:150,memberQuantity:2,distributionDimensionMm:300};
const stirrup=calculateBbs({...stirrupBase,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'DRAWING_SPECIFIED',hooks:{hookAngleDeg:135,hookExtensionMm:100,hookExtension2Mm:100}});assert.equal(stirrup.input.shape,'E');assert.equal(stirrup.output.cuttingLengthMm,1520);assert.equal(stirrup.output.totalBars,4);assert.equal(stirrup.output.totalLengthM,6.08);assert.equal(stirrup.output.totalWeightKg,3.75);assert.ok(stirrup.assumptions.length);
const tie=calculateBbs({...stirrupBase,shape:'COLUMN_TIE',stirrupWidthMm:250,stirrupDepthMm:450,linkDetailingMode:'DRAWING_SPECIFIED',hooks:{hookAngleDeg:135,hookExtensionMm:80,hookExtension2Mm:80}});assert.equal(tie.input.shape,'F');assert.equal(tie.output.cuttingLengthMm,1500);
for(const [dia,extension,cut] of [[8,80,1424],[10,100,1440],[12,120,1456],[16,160,1488]]){const seismic=calculateBbs({...stirrupBase,diaMm:dia,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'SEISMIC_IS13920_2016',dimensionBasis:'CENTRELINE',hooks:{hookAngleDeg:135}});assert.equal(seismic.input.linkDetailing.hookExtensionMm,extension);assert.equal(seismic.input.linkDetailing.hookExtension2Mm,extension);assert.equal(seismic.output.cuttingLengthMm,cut);assert.ok(seismic.trace.includes(`Hook extension rule = 10d extension with 75 mm minimum`));}
const drawing=calculateBbs({...stirrupBase,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'DRAWING_SPECIFIED',dimensionBasis:'INNER',hooks:{hookAngleDeg:135,hookExtensionMm:90,hookExtension2Mm:100}});assert.equal(drawing.input.dimensionsMm.W,250);assert.equal(drawing.input.dimensionsMm.D,450);assert.equal(drawing.output.cuttingLengthMm,1470);assert.equal(drawing.input.linkDetailing.totalBendDeductionMm,120);
const custom=calculateBbs({...stirrupBase,shape:'COLUMN_TIE',stirrupWidthMm:260,stirrupDepthMm:460,linkDetailingMode:'CUSTOM',dimensionBasis:'OUTER',hooks:{hookAngleDeg:135,hookExtensionMm:95,hookExtension2Mm:105}});assert.equal(custom.input.dimensionsMm.W,250);assert.equal(custom.input.dimensionsMm.D,450);assert.equal(custom.output.cuttingLengthMm,1480);
const ninety=calculateBbs({...stirrupBase,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'CUSTOM',hooks:{hookAngleDeg:90,hookExtensionMm:80,hookExtension2Mm:80}});assert.equal(ninety.input.linkDetailing.hookBendDeductionMm,20);assert.equal(ninety.output.cuttingLengthMm,1480);
assert.throws(()=>calculateBbs({...stirrupBase,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'SEISMIC_IS13920_2016',hooks:{hookAngleDeg:90}}));
assert.throws(()=>calculateBbs({...stirrupBase,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'DRAWING_SPECIFIED',hooks:{hookAngleDeg:135}}));
assert.throws(()=>calculateBbs({...stirrupBase,diaMm:0,shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:240,stirrupDepthMm:440,linkDetailingMode:'SEISMIC_IS13920_2016',hooks:{hookAngleDeg:135}}));
const ring=calculateBbs({...stirrupBase,memberType:'Column',shape:'CIRCULAR_RING',ringDiameterMm:300,barCountPerMember:3,hooks:{hookExtensionMm:50,hookExtension2Mm:50}});assert.equal(ring.input.shape,'G');assert.equal(ring.output.barsPerMember,3);assert.equal(ring.output.totalBars,6);assert.equal(ring.output.cuttingLengthMm,1042.5);assert.ok(ring.trace.some(x=>x.includes('π')));
for(const input of [{shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:0,stirrupDepthMm:100},{shape:'COLUMN_TIE',stirrupWidthMm:100,stirrupDepthMm:-1},{shape:'CIRCULAR_RING',ringDiameterMm:0},{shape:'CIRCULAR_RING',ringDiameterMm:250,barCountPerMember:0},{shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:100,stirrupDepthMm:100,spacingMm:0},{shape:'RECTANGULAR_STIRRUP',stirrupWidthMm:100,stirrupDepthMm:100,coverMm:200}])assert.throws(()=>calculateBbs({...stirrupBase,...input}));
console.log('BBS engine checks passed.');
